### ISSUE TITLE
setError does not clear async errors

### ISSUE THREAD

**Issue by mrfelton** [joepuzzo/informed#109]
I can call `setError(field, null)` to clear errors for a field. However, I can not clear async errors using this method.

**Comment by mrfelton** [comment]
Here is a hack that I;'m using to clear the async errors for a field:

```javascript
const formState = formApi.getState()
delete formState.asyncErrors.myField
formApi.setState(formState)
```

**Comment by joepuzzo** [comment]
V2 no longer supports async validation

**Comment by mrfelton** [comment]
> V2 no longer supports async validation

Any particular reason why?

**Comment by korhaliv** [comment]
> Way overcomplicated the lib. It turns out its very easy for a user to simply execute async code via an on change and then use the forms `setError` to set errors on the form.

How would you ensure async validation is run before form submit ? With field `onChange` handler it's easier, but still validation could be pending when user hits submit. With validate `onBlur` this problem seems to be even more pronounced: in this case user can hit submit before blurring the input and validation won't have a chance to complete
One way is to wrap submit and make sure to run all async validators on your own before calling form.submit.
Am I missing something here?

**Comment by joepuzzo** [comment]
Nope your not wrong. For now you would have to set some sort of external state to prevent your actual submission function ( a rest call or somthing ) from being called. I may add a lock method on the api that allows a user to lock the form ( so they dont need external state ) i also am not apposed to maybe eventually adding asny validation BUT im only going to do it if i figure out a way that does NOT drastically complicate lib. Specially i hate making submit async and then all of a suddon trivial form submission unit tests become horrible to deal with
