### ISSUE TITLE
Form level validation

### ISSUE THREAD

**Issue by markmckim** [joepuzzo/informed#111]
Hi,

I have a simple login form (with username & password fields).

I have successfully hooked up validation to each field (min length, max length etc.), but I would like to hook up validation on form submit to catch scenarios such as "incorrect username or password".

At the moment, I'm catching the login service response in my submit handler, then using the form api to push an error message into the error object for the last field on the screen (password).

This "works" but it doesn't "feel" right.

Is there a better way to 1) handle and 2) push form-level validation errors to the form?

I know I could also use asyncvalidation but its tied to a field level, so again, I would be pushing the login service response into the error object for the password field only, which feels wrong as it could be either the username OR password that is incorrect.

Thanks!

**Comment by joepuzzo** [comment]
What your doing is fine. Remember after you click that submit button, the form passes the initial validation, and u make call to backend, you are outside scope if informed. When u come back you have new data and need to manually tell the form lib about that change

**Comment by vfonic** [comment]
I also came here looking for form-level validation. I need to add this kind of validation rule (just one of the examples):

When both [lat,lng] and [address1, postal code, city] are empty, show "You must specify address or select on the map"

I have no idea how I'd achieve this with informed.

@markmckim regarding `errors.form`, I think it's a good idea. I'd call it `errors.base`. Just something I picked up from Rails:
https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-add
> attribute should be set to `:base` if the error is not directly associated with a single attribute.

I love informed's API. It's super simple and flexible. I'd love to see form-level validation, because I like having all validation in one place (especially since, for me, the fields depend on each other)

**Comment by joepuzzo** [comment]
I added form level validation in V2!!

**Comment by vfonic** [comment]
@joepuzzo YES!!! Thank you! :)

Where can I find out more how to use it? I couldn't find anything in the docs.

**Comment by joepuzzo** [comment]
Working on better docs for it but for now there is an example in the `FormState` section https://joepuzzo.github.io/informed/?selectedKind=Form&selectedStory=State&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel and also you can read about it in the props section of the docs

**Comment by vfonic** [comment]
This is great! I can use some schema package and validate all the form data against the given schema. Thank you!

**Comment by joepuzzo** [comment]
Remember tho this form level validation sets the form as a whole to invalid. Not individual fields.

**Comment by vfonic** [comment]
Bummer :(

I'd really love to have both. Do you think it's something you'd consider having in the future? I might take a look to see if I can find some time to make a PR.

**Comment by joepuzzo** [comment]
Well it’s easy achievd with field level validation or the use of the form API

**Comment by joepuzzo** [comment]
I dont think the form level validation should set individual fields error states

**Comment by joepuzzo** [comment]
And if two fields validation depend on each other then you can use informeds “notify” props

**Comment by vfonic** [comment]
I was thinking that form-level validation might return an object with keys being field names that failed validation and values being error messages.

This is how rails does it for example:
https://api.rubyonrails.org/classes/ActiveModel/Errors.html#method-i-keys

**Comment by joepuzzo** [comment]
@vfonic Done!! i added `validateFields` in the latest release. Now go ahead and use joi

**Comment by joepuzzo** [comment]
https://joepuzzo.github.io/informed/?selectedKind=Validation&selectedStory=Form%20Level%20Validation&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by markmckim** [comment]
@joepuzzo This is fantastic!! Thanks!

Just out of curiosity...do the two new form level functions support async validation in a similar manner to the individual fields?

(e.g. use case would be a login submit button which makes a service call, but when it fails, puts the entire form into error state)

**Comment by joepuzzo** [comment]
There is no longer support for async anything. It way overcomplicates the lib. That being said, it is very easy to use the form api to set an error manually

**Comment by markmckim** [comment]
Ah ok fair enough. Thanks for the clarification and thanks for adding the above features! 🎉

**Comment by vfonic** [comment]
Thank you @joepuzzo!!!

It seems this supports the form-level validation, but you can, from the errors object, know which fields are invalid, so that you can, for example, put a red border around those input fields. Correct?

**Comment by joepuzzo** [comment]
@vfonic a little confused as to what you are asking.. if you're asking about knowing when your field is in an error state then thats easy because its field error will be set. This can be done with either field or form level validation.. see this example with red border https://joepuzzo.github.io/informed/?selectedKind=CustomInputs&selectedStory=Creating%20Custom%20Inputs&full=0&addons=0&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by vfonic** [comment]
@joepuzzo Yes, that's what I meant: Can I have field level errors, from form level validation. Seems like it just works™!

Thanks!
