### ISSUE TITLE
Form-level change handler

### ISSUE THREAD

**Issue by acbabis** [joepuzzo/informed#113]
Suppose I want to submit a form with a 500ms debounce after any value is changed. Is there a way to do this without adding a handler to each input?

**Comment by joepuzzo** [comment]
Im a little confused. You want a debounce on the form submission? As in when you click the submit button? The confusion is because that should have nothing to do with the individual input handlers

**Comment by acbabis** [comment]
I want a form to be "auto-save". There is no submit button; it submits 500ms after the last keystroke. Currently, I'm putting my auto-save handler on each input, but I'd prefer to have it on the form itself

**Comment by ramiyahya** [comment]
The `formApi` prop gives you a handy little `submitForm` function. 

So you could create an `AutoSave` component that "submits" the form after every keystroke (debounced by 500ms). Instead of having the auto-save handler on each input, have the logic in your `AutoSave` component check the `formState` and trigger the `submitForm` function whenever the state is updated.

**Comment by acbabis** [comment]
Thanks @ramiyahya, I'll probably end up implementing something like this
