### ISSUE TITLE
Multiple buttons in <Form>

### ISSUE THREAD

**Issue by Leftium** [joepuzzo/informed#129]
Informed does not support multiple buttons very well. The desired behavior:
- Each button has its own onSubmit callback
- OR the onSubmit callback can be supressed (and onClick is handled, instead)
- OR the onSubmit callback passes data about which button was clicked

Specifically, for my desired Form:
- "Save" button should call my API to save
- "Delete" button should call my API to delete (then navigate back to previous page)
- "Cancel" button should navigate back to the previous page
- Hitting ENTER in any field should act like "Save"

I ran into these problems:
- I cannot prevent handleSubmit() from being called when handling a click on a button inside a Form
- I cannot not identify which button was pressed from the handleSubmit() callback; I only have the value of the fields
- If some buttons are moved outside the Form, it is more difficult to get access to the Form's state
- If all the buttons are moved outside the Form, typing ENTER no longer submits the form
- I would like to keep all the buttons together for layout/styling purposes.

I managed to create a Form with multiple buttons, but it would be nice if it didn't require the three work-arounds needed as shown in this sample:
- [livedemo](https://informed-cant-handle-multiple-buttons.glitch.me/?h=some+url&t=some+title) (check dev console for basic output)
- [relevant code](https://glitch.com/edit/#!/informed-cant-handle-multiple-buttons?path=app/components/LinkForm.cjsx:2:0) (functional React component written in CoffeeScript; search for "WORKAROUND")

Ideally, I could have multiple buttons inside a Form and either:
- control/prevent when onSubmit is triggered
- identify which button was pressed when handling onSubmit

Is there a better way to have multiple buttons inside a single Form?
Or is it possible modify Informed to support this case? (Like adding another parameter to the onSubmit callback that has details about which button was pressed)

**Comment by khendrikse** [comment]
Hey @Leftium, just to see if I understand correctly:
You want to have three buttons, one of them saves the form, the other deletes it and the other cancels?

And  the 'save' button should be kind of the default one? So if you press 'enter' inside the fields, that is the one you want to be triggered?

Looking at the code, and if I understand the library, and your needs correctly, you could:

Place the three different buttons inside the `<Form>` and ddd `type='submit'` to the 'save' button. This way the form will recognise this button as the one that does the submitting for the form.  You can actually remove the onSubmit prop from the `<Form>` component and just add the click handler to the save button. 

This way, if someone clicks the delete or cancel button, they will only trigger their own click handlers. Also, this way you only have three options, and since each of the three buttons have their own click handlers, you will always know which button was clicked.

Hopefully this helps! If not, let me know, maybe I should explain better, or maybe I don't understand the question.

**Comment by Leftium** [comment]
Thanks @khendrikse, that works beautifully!

Using your suggestion, I was able to [greatly simplify my Form](https://glitch.com/edit/#!/informed-multiple-buttons-hendrikse?path=app/components/LinkForm.cjsx):

``` coffeescript
LinkForm = () ->
  handleClick = (event) ->
    console.log "handleClick: #{event.target.value}"
    console.log LinkForm.formApi.getState().values
      
  <Form getApi={ (api) -> LinkForm.formApi = api } className="link-form">
    <label htmlFor='url'>URL</label>
    <Text field="url" initialValue="u"/>

    <label htmlFor='title'>Title</label>
    <Text field="title" initialValue="t"/>

    <div>
      <button onClick={handleClick} value="save"  >Save  </button>
      <button onClick={handleClick} value="delete">Delete</button>
      <button onClick={handleClick} value="cancel">Cancel</button>
    </div>
  </Form>
```
- Notice `type='submit'` wasn't needed; Form just clicks the first button it finds.
- Also, it's possible to combine all the click handlers and determine the button based on the event object.



It would be nice if I could access the Form's values without formApi (like the onSubmit callback), but I can live with that!
