### ISSUE TITLE
'window is not defined' using SSR

### ISSUE THREAD

**Issue by danielsarin** [joepuzzo/informed#13]
I'm trying to migrate from `react-form` to `informed` using `next.js`, but it throws the following error:

```
window is not defined

ReferenceError: window is not defined
    at Object.<anonymous> (/myproject/node_modules/informed/dist/index.js:1:271)
```

The webpack config probably adds the window reference. Any way to change it to make it would work with server side rendering? Or maybe I'm missing something?

**Comment by joepuzzo** [comment]
Ahh i don’t typically do server side rendering and have never used next.js so i have never run into this. That being said i can look to see if i can fix window getting transpiled in

**Comment by jangerhofer** [comment]
For what it's worth, replacing the single instance of `window` in the `dist/index` file with `null` fixes the NextJS SSR error and does not seem to impair the form functionality!  The `window` addition appears to be superfluous.  

I wish I had a better handle on Webpack such that I could be of use fixing the root of the problem, rather than the symptom...

**Comment by jangerhofer** [comment]
From a little digging, it looks like the solution is quite simple.  Just [one missing line](https://github.com/jangerhofer/informed/commit/fdc9d21ab8ed39fb57795e1d9be98c8a830a69f6) in the Webpack config to set a `globalObject`.

**Comment by joepuzzo** [comment]
I will give this a shot tomorrow!

**Comment by joepuzzo** [comment]
Hey I just added that line and released new version. Try it out !

**Comment by jangerhofer** [comment]
Looks good to me.  Running smoothly on v1.3.6!  Thanks for the speedy update!!

**Comment by joepuzzo** [comment]
Awesome closing
