### ISSUE TITLE
Form validation fails when using initialValues

### ISSUE THREAD

**Issue by jacargentina** [joepuzzo/informed#139]
I've downgraded to latest stable. In v2 the same form with same data is failing validation when I do submitForm

**Comment by jacargentina** [comment]
I'm adding a test. It seems related to using `initialValues`. If i remove those, it passes.

I'm getting this form state before the failing `expect`

```js
{ values: { greeting: 'hello' },
  touched: { greeting: true },
  errors: { greeting: null },
  pristine: false,
  dirty: true,
  invalid: true,
  submits: 1 }
```

I'll send a PR on this test so it helps on fixing @joepuzzo . Cheers!

**Comment by Jakobo** [comment]
I ran into this problem as well, but initial values weren't required. The validation submission is failing because the form state includes `errors: { greeting: null }`. It causes a validation failure because the Form Controller's `valid()` check passes through the lowdash's `_.values()`.

`ldvalues({greeting: null})` has a length of 1, causing ObjectMap's `empty() to return false.

Either of these code blocks would work to fix the issue:
```
// using _.pickBy + _.identity
// https://lodash.com/docs/4.17.11#pickBy
// https://lodash.com/docs/4.17.11#identity
class ObjectMap {
  static empty(object) {
    return ldvalues(ldpickby(object, ldidentity)).length === 0;
  }
  // ...
```

```
// using _.omitBy + _.nil
// effectively the inverse of the above, but yields the same result
// https://lodash.com/docs/4.17.11#omitBy
// https://lodash.com/docs/4.17.11#isNil
class ObjectMap {
  static empty(object) {
    return ldvalues(ldomitby(object, ldisnil)).length === 0;
  }
  // ...
```

Personally, I prefer the omitBy + nil for readability, as it would filter all null & undefined values out of the object in order for the length check to properly succeed.

I'll see about a pull request in the morning; it's a bit late here.

https://github.com/joepuzzo/informed/blob/master/src/FormController.js#L164
https://github.com/joepuzzo/informed/blob/master/src/ObjectMap.js

**Comment by joepuzzo** [comment]
No so your validation functions should not return null. If there is no error return undefined and this is not an issue.

**Comment by jacargentina** [comment]
So the issue is not an issue but a BREAKING CHANGE!

@joepuzzo you should make it clear this on the Release Notes please; previous versions handled `null` for validation but now all validation functions must be refactored to return undefined.

**Comment by joepuzzo** [comment]
Yup this was a miss in the changelog. I will update

**Comment by Jakobo** [comment]
Thanks @joepuzzo for the update. 🎉 I sent over a PR that has the changelog fix.
