### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by m1ch34lj0hns0n** [joepuzzo/informed#15]
Hi Joe, do you have any intentions of adding async validation into informed?

**Comment by joepuzzo** [comment]
So Async Validation is something that caused the codebase to get very complex and out of hand. So i have been putting a lot of thought into this. I have an idea for this to keep things clean and simple since people implement async stuff in many different ways and have all sorts of needs. So here it is: 

I want to simply add a `lock()` and `unlock()` function to the `formApi`. This will not allow the form to get locked so it can not try to submit while locked. Then a developer can chose to tie into whatever lifecycle hooks `informed` provides, such as `onChange` or `onBlur`. And they can asynchronously do what they need to and set an error before unlocking the form.

Note: when i design this i would design it such that if you called `lock()` more than once than you would need to call `unlock()` that same amount of times.

Also i would add a hook inside of `informed` that would also call a final `beforeOnSubmit` function so you could lock it before it submits and perform one final submission.

**Comment by joepuzzo** [comment]
Also im speaking off the cuff here ^^ i have not fully figured it out yet

**Comment by m1ch34lj0hns0n** [comment]
Thanks for the response Joe, I've managed to hack my way around this issue using callbacks for the time being. Looking forward to seeing your solution.

**Comment by joepuzzo** [comment]
Ok so im adding it lol

**Comment by joepuzzo** [comment]
Its in!! Go check out the docs
