### ISSUE TITLE
IE11 Expected Identifier

### ISSUE THREAD

**Issue by frank10gm** [joepuzzo/informed#163]
informed version 2.x.x doesn't work with IE 11.

Error code:
**SCRIPT1010: Expected Identifier**

**Comment by joepuzzo** [comment]
You will need to add the appropriate polyfills in your build

**Comment by frank10gm** [comment]
Thank you for your fast reply.
I tried everything, which polyfills do I need?

**Comment by joepuzzo** [comment]
Not off the top of my head. I know in my current app i have the following: 

```
 entry: [
    'babel-polyfill',
    path.resolve(__dirname, '../../src/index.js'),
  ],
```

**Comment by joepuzzo** [comment]
Ok so update. I just went through this Hell hole as well ( It was not fun ) As i too had to support IE11. The fix was as follows: 
**Assuming you are using babel and webpack**
1. Create a `babel.config.js` file NOT a `.babelrc` Read this stack overflow post https://stackoverflow.com/questions/54788809/babel-7-dont-compile-class-es6-which-in-node-modules
2. Add content to your `babel.config.js` file
Mine looks like this
```
module.exports = {
  presets: [
    '@babel/preset-react',
    [
      '@babel/preset-env',
      {
        targets: {
          ie: '11'
        },
        // Only polyfill things that need to be for the targets chosen i.e ie11
        useBuiltIns: 'entry'
      }
    ]
  ],
  plugins: [
    '@babel/plugin-transform-runtime',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-class-properties'
  ]
};
```
3. In your webpack config, add something like the following so that informed gets transpiled. 
```
 {
        test: /\.js$/,
        // exclude: /node_modules/,
        exclude: /node_modules\/(?!(debug|informed)\/).*/,
        use: ['babel-loader'],
      },
```

**Comment by frank10gm** [comment]
Hi man,
thank you very much.
I hate IE11 too.

**Comment by joepuzzo** [comment]
Also want to link to this issue for reference https://github.com/visionmedia/debug/issues/674
