### ISSUE TITLE
Manually set Option as selected

### ISSUE THREAD

**Issue by makcakaya** [joepuzzo/informed#165]
Version 1.10.12

Is there a way to manually set an <Option> as selected, so like <Option selected ... >? 

Also I cannot define id or ref property on <Option>. Is there a way to define those properties at least?

**Comment by joepuzzo** [comment]
So you should have no issues adding id on there. In order to get select and multiselect to work.. I think i currently "steal away the ref" because I use it internally. Maybe there is a way for me to expose it to you.

In terms of manually setting a selected option. You can use `informed`'s api and call `setValue` . See the form Api section of the docs

**Comment by joepuzzo** [comment]
@makcakaya Can i close this ?
