### ISSUE TITLE
initialValues along with useField yields undefined initially

### ISSUE THREAD

**Issue by FredyC** [joepuzzo/informed#184]
I must say that was rather a painful moment before I've debugged what's happening there. Apparently, the `initialValues` are ignored until the field is registered. I am not sure if it's an attempt for some optimization or a limitation of architecture, but I think it's wrong.

```jsx
<Form initialValues={{ listOfSomething: [] }}><FormSection /></Form>

const FormSection = () => {
  const { fieldState } = useField('listOfSomething')
  // fieldState is undefined on initial render
}
```

One can argue that I should be checking for value there to increase encapsulation and not rely on that initialValues will be set. That's a fair assumption, but it doesn't feel right to be forced to do it every time.

**Comment by joepuzzo** [comment]
So here is the issue with this. I designed informed with a key point in mind. And that is all fields should be independent of one another and independent of a Form if they want to be. BUT if they were within a form, then they would register themselves witht that form. Because of this however, until the field registers itself with the form then the useField wont have the registered data, i have been thinking a lot about this and may be able to do some playing to get registration to happen on initial render tho

**Comment by FredyC** [comment]
https://github.com/joepuzzo/informed/blob/48cef77d80bab4365100f85c718384efb538d5f5/src/hooks/useField.js#L178

Yea, `useEffect` feels like an obvious choice here as it can do dirty work of re-registering on field name change, but the tradeoff is it will run after the render. 

You should have a `useRef` there that basically keeps track if it was already registered. You can check that when returning value from `useField` call and run registration if hasn't happened yet. You can keep `useEffect` there for re-registration and cleanup, just make sure to check for that flag there as well to prevent double registration.

**Comment by joepuzzo** [comment]
I need to sit down and really think and rework the effect stuff

**Comment by joepuzzo** [comment]
I think i have solved this!

**Comment by joepuzzo** [comment]
@FredyC Try with the latest version

**Comment by joepuzzo** [comment]
I register the field right away now

**Comment by FredyC** [comment]
Sorry, I've kinda decided to go with Formik2 since it seemed not much is going to happen in here. It's good you have figured it out for other people for sure.
