### ISSUE TITLE
React error upon using <Select> component

### ISSUE THREAD

**Issue by joewestcott** [joepuzzo/informed#3]
````
Uncaught Error: Element ref was specified as a string (select) but no owner was set. This could happen for one of the following reasons:

Element ref was specified as a string (select) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.

**Comment by joepuzzo** [comment]
I will look into this as soon as possible

**Comment by joepuzzo** [comment]
Im not getting this error. Could you paste a source code snippet and let me know what browser you are using?

**Comment by joewestcott** [comment]
I think it's to do with the 3rd point above, since this library has `react` listed as a dependency.
Can you list `react` and `react-dom` as peerDependencies, and broaden the range a bit?
[Example from react-form](https://github.com/react-tools/react-form/blob/master/package.json#L64)
Thanks.

For reasons I can't yet work out, this isn't a problem with npm. (I was using yarn)

**Comment by joepuzzo** [comment]
Oh yup i can make those dev dependencies

**Comment by joepuzzo** [comment]
Done

**Comment by joewestcott** [comment]
Thankyou. This has now fixed my issue.

**Comment by kyawkyawsoezhu** [comment]
I'm Implementing a library using `informed` and error occur when I use `<Select>`, But when i use `<Select>` in main application it works.

I'm pretty sure that it's not **multiple copies of React loaded** issue because when I remove [ref](https://github.com/joepuzzo/informed/blob/3f5e8974ba0bc9efe30b9cfb3361d99afb957c34/src/components/form-fields/Select.js#L43) from `<Select>` no error
