### ISSUE TITLE
Error When Using Array for formApi.getValue()

### ISSUE THREAD

**Issue by cjkoepke** [joepuzzo/informed#4]
In the previous library, I could retrieve a nested value by passing the path array to the `formApi.getValue()` method. However, when using it via `informed`, I'm getting the following error:

```js
Uncaught TypeError: e.replace is not a function
```

While debugging I noticed that when you build the array from the string equivalent, `prop.nested`, there is no check to see if the array is already there: https://github.com/joepuzzo/informed/blob/master/src/ObjectMap/index.js#L74

It might be useful to see if this is already present to allow variously data formats for lookup.

**Comment by joepuzzo** [comment]
Yes this was because i wanted to simplify the field syntax to only allow strings. Technically i could check for a path array. But this was a conscious decision. I did not want to have to document path arrays and field syntax strings. Just wanted to keep things simple in informed. Is there a reason you cant use the string syntax?

**Comment by joepuzzo** [comment]
Why not generate the string instead of array path ?

**Comment by cjkoepke** [comment]
In the original library, I'm just grabbing the `fieldName` value from the `fieldApi`, which is already in array format.

**Comment by cjkoepke** [comment]
Oh, actually sorry — when I generate the path for a conditionally related field, that is definitely in my control.

**Comment by joepuzzo** [comment]
So can i close?

**Comment by cjkoepke** [comment]
Yeah, thanks. I still think it'd be nice to be able to use both, but that's just my opinion. ;-)
